
resolver: lts-18.27
allow-newer: true

flags:
  liquid-fixpoint:
    devel: true 

packages:
- '.'


extra-deps:
- hashable-1.3.5.0
- rest-rewrite-0.3.0
- smtlib-backends-0.2
- smtlib-backends-process-0.2
- smtlib-backends-z3-0.2

nix:
  packages: [z3]
